name: hello-world
on: push
jobs:
   my-job:
      runs-on: ubuntu-latest
      steps:
        - name: my-step
          run: echo "Hello World!"
        - name: my-workshop
          run: echo "DevOps"
        - name: AN-sescion
          run: echo "Hands On Workshop"
          
